#!/bin/sh

self="$(basename "$0")"

colorize() {
	sd ^ "\033[${1}m" | sd $ '\033[0m'
}

reindent() {
	sd '^[ \t]*' '   '
}

balanceavax() {
	curl -sSX POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["'"$1"'","latest"],"id": 1}' \
		-H 'content-type:application/json;' https://api.avax.network/ext/bc/C/rpc |
		jq -r .result |
		upper |
		sd ^0X '' |
		xargs -I_ echo 'ibase=16; _/DE0B6B3A7640000' |
		bc -l
}


case $1 in


	(cchain)
		case $2 in

			(assets)
			;;

			(balance)
				case $3 in
					(avax)
						if [ -n "$4" ]; then
							balanceavax "$4"
						else
							>&2 echo "❯ $self cchain balance .. \033[31m<wallet_address>\033[0m"
						fi
					;;
					(*) # case-level-2
						echo "❯ available assets"; printf '
							avax
						' | reindent | colorize 33
					;;
				esac
			;;

			(*) # case-level-1
				echo "❯ available commands"
				printf '
					balance
				' | reindent | colorize 33

			;;

		esac
	;;


	(*)
		echo "❯ available commands"
		printf '
			cchain
		' | reindent | colorize 33
	;;

esac
