#!/usr/bin/env python3
"beautiful bar chart"
from cairo import ImageSurface, Context, FORMAT_ARGB32, FONT_SLANT_NORMAL
from datetime import datetime
import sys

HEIGHT = 800
WIDTH  = int(800*(16.0/9.0))
FONT_SIZE = WIDTH/35
GAP = 0.03

hex2rgb = lambda h: tuple(int(h.lstrip('#')[i:i+2], 16) for i in (0, 2, 4))
hexa2rgba = lambda h: tuple(int(h.lstrip('#')[i:i+2], 16) for i in (0, 2, 4, 6))
zeronerange = lambda l: tuple(map(lambda x: x/255.0, l))

def draw_background(ctx, rgb, width, height):
    "draws a background fill"
    ctx.set_source_rgb(*rgb)
    ctx.rectangle(0, 0, width, height)
    ctx.fill()

with ImageSurface(FORMAT_ARGB32, WIDTH, HEIGHT) as surface:
    context = Context(surface)
    draw_background(context, zeronerange(hex2rgb("#2b3339")), WIDTH, HEIGHT)
    #                                            "#1d2021"

    context.select_font_face('Times New Roman', FONT_SLANT_NORMAL)

    TEXT = sys.argv[1]
    context.set_font_size(FONT_SIZE)
    (x, y, w, h, dx, dy) = context.text_extents(TEXT)
    context.move_to((w-dx)+HEIGHT*GAP, h+HEIGHT*GAP)
    context.set_source_rgb(*zeronerange(hex2rgb("#3a94c5")))
    context.show_text(TEXT)

    TEXT = sys.argv[2]
    context.set_font_size(FONT_SIZE*.8)
    (x1, y1, w1, h1, dx1, dy1) = context.text_extents(TEXT)
    context.move_to((w-dx)+HEIGHT*GAP, h+h1+HEIGHT*GAP*2)
    context.set_source_rgba(*zeronerange(hexa2rgba("#3a94c5aa")))
    context.show_text(TEXT)

    # TEXT = datetime.now().strftime('%Y-%m-%d')
    # context.set_font_size(FONT_SIZE*.8)
    # (x2, y2, w2, h2, dx2, dy2) = context.text_extents(TEXT)
    # context.move_to((w-dx)+HEIGHT*GAP, h+h1+h2+HEIGHT*GAP*3)
    # context.set_source_rgba(*zeronerange(hexa2rgba("#3a94c5aa")))
    # context.show_text(TEXT)

    data = []
    for line in sys.stdin:
        data.append(float(line.strip().strip('\\t')))

    context.set_source_rgb(*zeronerange(hex2rgb("#DFA000")))

    len_data = len(data)
    stroke_width = (WIDTH/len_data)*.9
    xc = 0
    for d in data:
        context.rectangle(xc, HEIGHT-d, stroke_width, d);
        context.fill()
        xc += stroke_width*(1+GAP)

    context.set_source_rgb(*zeronerange(hex2rgb("#dfa000")))

    l = max(data)*.618
    context.rectangle(WIDTH*.1, HEIGHT - l, WIDTH*.85, 5);
    context.fill()

    context.set_font_size(FONT_SIZE*.7)
    (x3, y3, w3, h3, dx3, dy3) = context.text_extents(str(int(l)))
    context.move_to(WIDTH*.95+w3/4, HEIGHT-l+h3/2)
    context.show_text(str(int(l)))

    out = 'bar-chart.png'
    surface.write_to_png(out)
    print(out)
