#!/bin/sh

#                ╭───────────column-date2timestamp──────────╮
#                Maintainer:     ihsan, ihsanl[at]pm[dot]me │
#                Last Change:    @1595343471                │
#                First Appeared: @1595343471                │
#                License:        MIT                        │
#                Status:         NOT WORKING                │
#                ╰──────────────────────────────────────────╯

SEPARATOR="\t"
COLUMNNUMBER="$1"

awk -F"$SEPARATOR" '{OFS="'"$SEPARATOR"'"; $'"$COLUMNNUMBER"'=strftime("%s", $'"$COLUMNNUMBER"'); print}'

