#!/bin/sh

src=/Users/ihsan/Sync/code/local/cosmopolitan/
out=$(echo "$1" | cut -f1 -d.)

x86_64-elf-gcc -g -Os -static -nostdlib -nostdinc -fno-pie -no-pie \
	-mno-red-zone -fno-omit-frame-pointer -pg -mnop-mcount \
	-o "$1"om.dbg "$1" -fuse-ld=bfd -Wl,-T,${src}/ape.lds \
	"$@" -include ${src}/cosmopolitan.h ${src}/crt.o ${src}/ape.o \
	${src}/cosmopolitan.a && x86_64-elf-objcopy -S -O binary "$1"om.dbg "$out"

test "$2" = '-d' || { rm -rf "$1"om.dbg; }
