#!/usr/bin/env python3

from eth_keys import keys
from secrets import token_hex
import sys

n = 1

if len(sys.argv) > 1:
    n = int(sys.argv[1])

for i in range(n):
    k = token_hex(32)
    print(keys.PrivateKey(bytes.fromhex(k)).public_key.to_checksum_address(),
          k,
          sep='\t')
