#!/usr/bin/env python3

from sys import stdin
from sha3 import keccak_256

def fixedlen(x):
    return x.zfill(64)

def f(prototype: str):
    """
    >>> balance_function = f('balanceOf(address)')
    """
    prototype = prototype.replace(', ', ',')
    def g(*args):
        selector = '0x'+keccak_256(prototype.encode()).hexdigest()[:8]
        args     = ''.join(map(fixedlen, args))
        return selector+args
    return g

if __name__ == '__main__':
    for line in stdin:
        prototype, params = line.split(')', 1)
        prototype += ')'
        function = f(prototype)
        params = params[1:-2].replace(', ', ',').replace("'", '').split(',')
        print(function(*params))
