#!/usr/bin/env python
"""
format-eksi-entry - pretty print an one eksi entry per line from html input

license: MIT
"""

NORMAL      = "\033[31m"
RED         = "\033[31m"
GREEN       = "\033[32m"
YELLOW      = "\033[33m"
BLUE        = "\033[34m"
PURPLE      = "\033[35m"
AQUA        = "\033[36m"
LIGHTGRAY   = "\033[37m"
GRAY        = "\033[90m"
LIGHTRED    = "\033[91m"
LIGHTGREEN  = "\033[92m"
LIGHTYELLOW = "\033[93m"
LIGHTBLUE   = "\033[94m"
LIGHTPURPLE = "\033[95m"
LIGHTAQUA   = "\033[96m"
WHITE       = "\033[97m"
RESET       = "\033[00m"


import sys
import textwrap
from bs4 import BeautifulSoup
for entry in sys.stdin.readlines():

    entry  = BeautifulSoup(entry, 'html.parser')
    author = entry.find("li")["data-author"].strip()
    fav     = entry.find("li")["data-favorite-count"].strip()
    date    = entry.find("a", {"class": "entry-date"}).text.strip()
    content = entry.find("div", {"class": "content"}).text.strip()
    content = entry.find("div", {"class": "content"}).text.strip()
    info    = f"[{fav}], [{author}]\n[{date}]"

    print('''[{c1}{x}{r}] {c2}{y}{r} {c3}{z}{r}\n{c}\n'''.format(
        c1=YELLOW, c2=AQUA, c3=RED, r=RESET, x=fav, y=author, z=date,
        c=textwrap.fill(content, 80)))
