#!/bin/sh

indent="\t"
lineseparator=$(printf '\-%.0s' {1..78})
esc=$(printf '\033[')

sed "
s/File.*\/\(.*\/\)/\"\1/g;
/Traceback/d;
s/\(.*line [0-9]*.*\)/$lineseparator\n\1/g;
\$s/^/$lineseparator\n\n/g;
s/[ \t]*\"\([^\"]*\)\", line \([0-9]*\), in \(.*\)\$/${esc}34m\2${esc}0m - \1 - \3/g;
s/\(^[0-9]* -\)\(.*\) -/\1${esc}35m\2{$esc}0m -/g;
"

# TODO: better colored output

# TEST:
#   cd /Users/ihsan/Sync/code/github.com/ihsanturk/stock-market-data
#   format-pyerr < err.py
