#!/usr/bin/env python3

import sys
import tempfile
import functional

import color

hex2bmp = functional.pipe(
        color.revhex,
        "424d1e000000000000001a0000000c0000000100010001001800{}00".format,
        bytearray.fromhex)

def main(hexrgb):
    "creates temp file writes bmp data to it and prints the out file path"
    (_, path) = tempfile.mkstemp(suffix='.bmp')
    with open(path, 'wb') as out:
        out.write(hex2bmp(hexrgb))
        out.close()
        print(path)

if __name__ == '__main__':
    tuple(map(main, sys.stdin))
