#!/bin/sh

# deps: usage

title="$(basename "$0")"; desc='small github util.'
args='(clone|search) [ -h ]'
opts='
c[lone] <url>
-h   show this help screen'
usg() { usage "$title - $desc" "$title $args" "$opts"; }

case "$1" in

	(c|cl|clo|clon|clone)

		git clone "$*"

	;;
	(s|se|sea|sear|searc|search)

		tr -u ' ' '+' | xargs -I_ open https://github.com/search?q=_

	;;

esac

while getopts :h args; do case $args in
	(h) usg; exit 0 ;;
	([?]) usg; exit 2 ;;
esac; done

