#!/usr/bin/env python3
"adds white border to a png image"

import cairo
from cairo import ImageSurface, Context
import sys
import os

hex2rgb = lambda h: tuple(int(h.lstrip('#')[i:i+2], 16) for i in (0, 2, 4))
zeronerange = lambda l: tuple(map(lambda x: x/255.0, l))

if not sys.argv[1:]:
    print('add-border \033[31m<image.png>\033[0m', file=sys.stderr)
    sys.exit(1)
else:
    with ImageSurface.create_from_png(sys.argv[1]) as surface:
        context = Context(surface)

        W = surface.get_width()
        H = surface.get_height()
        I = min(W, H)
        S = I*.007
        GAP = .1

        context.set_line_width(S)
        context.set_source_rgb(*zeronerange(hex2rgb('#aaaaaa')))
        context.rectangle(I*GAP, I*GAP, W-(I*GAP*2), H-(I*GAP*2))
        context.stroke()

        d = os.path.dirname(sys.argv[1])
        d+= '/' if any(d) else ''
        n, e = os.path.splitext(os.path.basename(sys.argv[1]))
        out = f'{d}bordered-{n}{e}'

        surface.write_to_png(out)
        print(out)
