#!/bin/sh

while read -r line; do
	case $line in
		([0-9.,]*)
			if (echo $line | egrep -q '\.'); then
				if (echo $line | egrep -q '\.0*$'); then
					exit 0;
				else
					exit 1;
				fi
			else
				exit 0;
			fi
		;;
		(*)
			exit 1
		;;
	esac
done

