#!/usr/bin/env python

from sys import argv, stdin, stderr

if len(argv) < 2:
    print('echo 5 | multiply \033[31m<number>\033[0m', file=stderr)
else:
    for line in stdin:
        print(float(argv[1]) * float(line))
