#!/bin/sh

# V1 --------------------------------------------------------------------------
# exiftool -overwrite_original -tagsfromfile "$1" "$2"

# V2 --------------------------------------------------------------------------
targetextension=$(echo "$2" | sed 's/.*\.\([^\.]*\)$/\1/g')
tmpname="$2-fixed.$targetextension"
ffmpeg -i "$1" -i "$2" -map 1 -map_metadata 0 -c copy "$tmpname" &&
	mv "$2" /tmp && mv "$tmpname" "$2"
