#!/bin/sh

file=~/et/log/life

main() {
	while read -r line; do
		[ -n "$line" ] &&
			count="$(wc -l < "$file" | sed 's/ *//')"
			printf "%s\t%s\t%s\n" \
				"$count" \
				"$(date +%s)" \
				"$line" \
			>> "$file"
			echo "$count"
	done;
}

# fuckoff argument means *don't use any dependencies*
if ! [ "$1" = "fuckoff" ]; then
	if which -s rlwrap; then
		rlwrap "$0" fuckoff;
	else
		main;
	fi
else
	main;
fi

