#!/usr/bin/env python3
"random line of a file"

import sys
import random

if __name__ == '__main__':
    if len(sys.argv) < 2:
        import color
        sys.stderr.write(f'random-line {color.err("<file>")}\n')
        sys.exit(1)
    else:
        with open(sys.argv[1]) as f:
            lines = f.readlines()
        print(random.choice(lines))

