#!/bin/sh

usage() {
	commandline='echo <channel_url> | telegram-channel-id'
	>&2 printf "usage:\n\t\033[33m$commandline\033[0m\n";
}

case $1 in
	(-h|--help) usage; exit 0;;
esac

echo paste the URL of your channel on web.telegram.org
while read -r line; do
	grep --line-buffered 'web.telegram.org.*p=' |
		echo "$line" | sed 's/.*p=c\([^_]*\).*/-100\1/g'
done
