#!/bin/sh

# deps: usage, useragent, twitter-guest-token, twitter-bearer-token

title='twitter'; desc='username -> user id'
usg() { usage "$title - $desc" "echo elonmusk | twitter-user-id"; }
while getopts :h args; do case $args in
	(h) usg; exit 0;;
	([?]) usg; exit 2;;
esac; done

header_auth="authorization: $(twitter-bearer-token)"
header_bearer="x-guest-token: $(twitter-guest-token)"

while read -r user; do
	url="https://twitter.com/i/api/graphql/Vf8si2dfZ1zmah8ePYPjDQ/UserByScreenNameWithoutResults?variables=%7B%22screen_name%22%3A%22${user}%22%2C%22withHighlightedLabel%22%3Afalse%7D"
	[ -n "$user" ] &&
		response=$(curl -sSLA "$(useragent)" -H "$header_auth" -H "$header_bearer" "$url")
	if (echo $response | grep -q errors); then
		echo $response | jq -r .errors.message
	else
		echo $response | jq -r .data.user.rest_id
	fi
done
