#!/bin/bash

# youtube-subtitle 
# Extract YouTube auto subtitle from a video.

usage() { echo "$(basename "$0"): <youtube-video-url> <output-file>"; }
if [ "$1" = "" ] || [ "$2" = "" ]; then usage; exit 1; fi

URL="$1"
fn="$2"
lang=en
youtube-dl -o "$fn" --write-auto-sub --sub-lang $lang --skip-download "$URL"

# Delete lines that starts with a number or contains <c>.
sed -i.bak -E -e '/(^[0-9])|<c>/d' "$fn"*

awk '!x[$0]++' "$fn"* | awk NF | tr '\n' ' ' | fold -s > tmp 
